using namespace std;
void myinit(void);
void display(void);
void drawTree(struct vertex treePoints[]);
void MidpointCircle(int radius, int cx, int cy);
void drawReverse(int radius, int cx, int cy);
int circumference(int radius);
void lineDDA (int x0, int y0, int xEnd, int yEnd);
int numPoints(int radius, int cx, int cy);
void circle(int radius, int cx, int cy, struct vertex tp[]);
